### ISSUE TITLE
Checklist V1.0.0

### ISSUE THREAD

**Issue by Tjoosten** [Tjoosten/laravel#37]
- [ ] All text free from spelling errors?
- [ ] Content has been placed consistently?
- [ ] Page & content formatting has been tested? 
- [ ] Print stylesheet exsts and tested? 
- [ ] Meta data has been included and is appropriate?
- [ ] Page titles are descriptive ans SEO friendly?
- [ ] Image have appropriate alt text?
- [ ] Title attributes are appropriate ans SEO friendly? 
- [ ] Favicon has been created and displays correctly?
- [ ] Footer of source includes copyright and link to the site creator? 
- [ ] HTML has passes validation? 
- [ ] CSS has passed validation?
- [ ] The are no broken links? 
- [ ] Javascript is error free? 
- [ ] Added WAI-ARIA support? 
- [ ] Displays é functions correctly in IE6? 
- [ ] Displays & functions correctly in IE7?
- [ ] Displays & functions correctly in IE8?
- [ ] Displays & functions correctly in Firefox (MAC & PC)? 
- [ ] Displays & functions correctly in Chrome (MAC & PC)?
- [ ] Displays & functions correctly in Safari (MAC and or PC)?
- [ ] Displays & functions correctly in Opera (MAC & PC)?
- [ ] Tested as 1024 x 768 resolution? 
- [ ] Tested at larger resolutions? 
- [ ] Forms have been tested and processed correctly?
- [ ] Required fields have been tested? 
- [ ] Froms send to correct recipient?
- [ ] Web statistics package installed and operational? 
- [ ] 404 Page exists and informative? 
- [ ] Is your wabsite backed up? 
- [ ] Is your website monitored?
